version: "3"
services:
 app:
  restart: always
  build: .
  command: "python3 manage.py runserver 0.0.0.0:8000 --noreload"
  volumes:
   - .:/code
   - /home/jns/Documents/mdict:/code/media/mdict/doc
  ports:
   - "8000:8000"
